// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbvT4bV0HAnQml133hX9QabcJ8bpfsCg8',
    appId: '1:674201850117:web:ad0a53278338c8f374a76c',
    messagingSenderId: '674201850117',
    projectId: 'login-app-636a6',
    authDomain: 'login-app-636a6.firebaseapp.com',
    storageBucket: 'login-app-636a6.firebasestorage.app',
    measurementId: 'G-TRK991WDJZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM3fuKqHi3tZCTMp7CQkk03w5QyrJZR1k',
    appId: '1:674201850117:android:785b4aa8a704d90374a76c',
    messagingSenderId: '674201850117',
    projectId: 'login-app-636a6',
    storageBucket: 'login-app-636a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaIiLaVGBgJhMKn7uci1WZRHztAaQ4ToY',
    appId: '1:674201850117:ios:35bbdfd711b439cb74a76c',
    messagingSenderId: '674201850117',
    projectId: 'login-app-636a6',
    storageBucket: 'login-app-636a6.firebasestorage.app',
    iosBundleId: 'com.example.loginApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaIiLaVGBgJhMKn7uci1WZRHztAaQ4ToY',
    appId: '1:674201850117:ios:35bbdfd711b439cb74a76c',
    messagingSenderId: '674201850117',
    projectId: 'login-app-636a6',
    storageBucket: 'login-app-636a6.firebasestorage.app',
    iosBundleId: 'com.example.loginApp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbvT4bV0HAnQml133hX9QabcJ8bpfsCg8',
    appId: '1:674201850117:web:0ec5db21dc3f056774a76c',
    messagingSenderId: '674201850117',
    projectId: 'login-app-636a6',
    authDomain: 'login-app-636a6.firebaseapp.com',
    storageBucket: 'login-app-636a6.firebasestorage.app',
    measurementId: 'G-B35DZHWRJH',
  );
}
